version: '3'

volumes:
  pg_data:
  media_volume:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - media_volume:/media
      - static_volume:/backend_static
    depends_on:
      - db    
  
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    build: ./nginx/
    ports:
      - 9000:80
    volumes:
      - media_volume:/media
      - static_volume:/static
    depends_on:
      - backend      
